CREATE TABLE NATION
(
ID int,
NAME_ID varchar(255),
DATE_ADDED date,
SHORT_NAME varchar(255),
THREE_LETTER_NAME varchar(255),
NATIONALITY_NAME varchar(255),
NICKNAME varchar(255),
CAPITAL varchar(255),
CONTINENT varchar(255),
REGION varchar(255),
REPUTATION number,
ECONOMIC_FACTOR number,
FA_POWER number,
YEARS_FOR_NAT number,
STATE_OF_DEVELOPMENT number,
GAME_IMPORTANCE number,
FA_PATIENCE number,
YOUTH_RATING number,
R1 number,
G1 number,
B1 number,
R2 number,
G2 number,
B2 number,
R3 number,
G3 number,
B3 number,
HOME_SHIRT number,
HOME_SHORTS number,
HOME_SOCKS number,
AWAY_SHIRT number,
AWAY_SHORTS number,
AWAY_SOCKS number,
REPLACE_NATION varchar(255),
CURRENCY varchar(255),
LANGUAGES varchar(255)
);

CREATE TABLE AGREEMENT 
(
  ID int,
  NAME_ID varchar(255),
  NATION_STRING varchar(255)
);

CREATE TABLE CITY
(
  ID number,
  NATION varchar(255),
  LANGUAGE varchar(255),
  ATTRACTION number,
  INHABITANTS_RANGER number,
  CITIZEN_DESCRIPTION varchar(255),
  LATITUDE varchar(255),
  LONGITUDE varchar(255),
  ALTITUDE varchar(255),
  WEATHER varchar(255),
  LOCAL_REGION varchar(255),
  DATE_ADDED date
  );
  
  
CREATE TABLE CLUB
(
  ID number,
  NAME_ID varchar(255),
	SHORT_NAME varchar(255),
	SIX_LETTER_NAME varchar(255),
  NICKNAME varchar(255),
  SECOND_NICKNAME varchar(255),
	NATION varchar(255),
	BASED_NATION varchar(255),
	CONTINENTAL_NATION varchar(255),
	CITY varchar(255),
	STATUS number,
	MORALE number,
	REP number,
	STADIUM varchar(255),
	TRAINING number,
	YOUTH_COACHING number,
	YOUTH_FACILITIES number,
	YOUTH_RECRUITMENT number,
	R1 number,
	G1 number,
	B1 number,
	R2 number,
	G2 number,
	B2 number,
	R3 number,
	G3 number,
	B3 number,
  HOME_SHIRT number,
	HOME_SHORTS number,
	HOME_SOCKS number,
	AWAY_SHIRT number,
	AWAY_SHORTS number,
	AWAY_SOCKS number,
	THIRD_SHIRT number,
	THIRD_SHORTS number,
	THIRD_SOCKS number,
	COMPETITION varchar(255),
	HAS_RESERVES number,
	HAS_U19S number,
	MIN_AGE number,
	MAX_AGE number,
	BALANCE number,
	TRANSFER number,
	WAGES number,
	SEASON_TICKETS number,
	FAN_LOYALTY number,
	FAN_PASSION number,
	FAN_PATIENCE number,
	FAN_AFFLUENCE number,
	FAN_TEMPERAMENT number,
	AR1 number,
	AG1 number,
	AB1 number,
	AR2 number,
	AG2 number,
	AB2 number,
	AR3 number,
	AG3 number,
	AB3 number,
	HAS_THIRD_KIT number,
  DATE_ADDED date
);

CREATE TABLE STADIUM
(
	ID number,
	NAME_ID varchar(255),
	DATE_ADDED date,
	CITY varchar(255),
	CAPACITY number,
	SEATING_CAPACITY number,
	EXPANSION_CAPACITY number,
	USED_CAPACITY number,
	PITCH_TYPE number,
	PITCH_CONDITION number,
	IS_COVERED number,
	RETRACT_ROOF number,
	UNDERSOIL_HEATING number,
	STATE number
);